### ISSUE TITLE
unpredictable results when fingerprinting path main.js

### ISSUE THREAD

**Issue by vvvvalvalval** [pointslope/boot-fingerprint#3]
I have an index.html that looks like this:

```
<!doctype html>
<html>
  <head>
    <title>hi, SNCF!</title>


    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

    <!-- BandSquare's stylesheets -->
    <link rel="stylesheet" href="${main.css}"/>
  </head>

  <body>
        <!-- Here goes the application dynamic content -->
        <div id="container" class="container-fluid"/>

        <!-- Bootstrap: Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>

        <!-- BandSquare's JS -->
        <script type="text/javascript" src="${main.js}"></script>
  </body>
</html>
```

In summary, I'm fingerprinting files `main.css` and `main.js`.

I have observed strange behaviour about the `main.js` path: sometimes, the output is the expected `"main.js?v=40caa02d4a69adab2fda53a1c2423d31cd1527bf"`, and sometimes, it's something else completely, such as `"out/boot/cljs/main.js?v=30e6d0c8207d72b34645fc87c4244da53abf012a"`.

I have not been able to discern any pattern as to when this happens. Something tells me that the [`find-asset-file`](https://github.com/pointslope/boot-fingerprint/blob/9c6c31d18fcbb5d3ff053b2f1907f4105ca86a04/src/pointslope/boot_fingerprint/fingerprint.clj#L12) function which relies on a regular expression to find the file is what causes this behaviour.

**Comment by ddeaguiar** [comment]
Hmm, I'll take a look. Thanks for reporting this!

**Comment by ddeaguiar** [comment]
@vvvvalvalval This change should resolve your issue. The latest 0.1.1-SNAPSHOT release includes it.
