### ISSUE TITLE
Absolute Path Assets

### ISSUE THREAD

**Issue by AdamFrey** [pointslope/boot-fingerprint#5]
Currently this task only supports relative paths. When I tried to fingerprint a file with 

```
<link rel="stylesheet" src="${/css/main.css}" />
```

in my project, then `find-asset-file` returns `nil` and the task blows up whenever it tries to calculate the `sha` of `nil`. Would you accept a PR that handles both relative and absolute paths?

**Comment by christianromney** [comment]
Absolutely. That sounds great.

**Comment by christianromney** [comment]
Thanks for the contribution, Adam.
